# Generated by Django 3.2.7 on 2021-09-06 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_userprofile_diseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Ввеите последние 10 цифр номера телефона. в формате: '1234567891'.", regex='^\\d{10}$')], verbose_name='номер телефона'),
        ),
    ]
