# Generated by Django 3.2.7 on 2021-10-11 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Введите последние 10 цифр номера телефона. в формате: '1234567891'.", regex='^\\d{10}$')], verbose_name='номер телефона'),
        ),
    ]
