# Generated by Django 3.2.7 on 2021-11-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211020_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
