# Generated by Django 3.2.7 on 2021-09-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210905_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='diseases',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
