version: '3.2'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kpk
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: fitness
  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
