# Generated by Django 3.2.7 on 2021-09-06 02:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='название услуги')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='цена')),
                ('desc', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='имя')),
                ('surname', models.CharField(max_length=32, verbose_name='фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=32, verbose_name='отчество')),
                ('gender', models.CharField(blank=True, choices=[('м', 'мужской'), ('ж', 'женский')], max_length=1, verbose_name='пол')),
                ('address', models.CharField(max_length=128, verbose_name='адрес')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Ввеите последние 10 цифр номера телефона. в формате: '1234567891'.", regex='^\\d{10}$')], verbose_name='номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.service')),
                ('trainer', models.ManyToManyField(to='mainapp.Trainer', verbose_name='тренер')),
                ('user', models.ManyToManyField(related_name='serv_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
