# Generated by Django 3.2.7 on 2021-10-11 05:33

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recording',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'услуга', 'verbose_name_plural': 'услуги'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AddField(
            model_name='recording',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recording',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='стоимость занятия за час в рублях'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Введите последние 10 цифр номера телефона. в формате: '1234567891'.", regex='^\\d{10}$')], verbose_name='номер телефона'),
        ),
    ]
